# Some pairs have been disabled due to a lack of candle data.
# You can restore them to test within recent months.

routes = [
    ('FTX Futures', 'ETC-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    # ('FTX Futures', 'LUNA-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'FIL-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    # ('FTX Futures', 'FTM-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'ETH-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'DOT-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'XTZ-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'BNB-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'NEO-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'SOL-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'LINK-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'XLM-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'MATIC-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'TRX-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'BTC-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'AAVE-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'ALGO-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'ADA-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'ATOM-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'XRP-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'LTC-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    # ('FTX Futures', '1INCH-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),
    ('FTX Futures', 'BCH-USD', '15m', 'ewoexit2708', '86lZ6^AX3'),

]
extra_candles = [
    ('FTX Futures', 'ETC-USD', '1h'),
    # ('FTX Futures', 'LUNA-USD', '1h'),
    ('FTX Futures', 'FIL-USD', '1h'),
    # ('FTX Futures', 'FTM-USD', '1h'),
    ('FTX Futures', 'ETH-USD', '1h'),
    ('FTX Futures', 'DOT-USD', '1h'),
    ('FTX Futures', 'XTZ-USD', '1h'),
    ('FTX Futures', 'BNB-USD', '1h'),
    ('FTX Futures', 'NEO-USD', '1h'),
    ('FTX Futures', 'SOL-USD', '1h'),
    ('FTX Futures', 'LINK-USD', '1h'),
    ('FTX Futures', 'XLM-USD', '1h'),
    ('FTX Futures', 'MATIC-USD', '1h'),
    ('FTX Futures', 'TRX-USD', '1h'),
    ('FTX Futures', 'BTC-USD', '1h'),
    ('FTX Futures', 'AAVE-USD', '1h'),
    ('FTX Futures', 'ALGO-USD', '1h'),
    ('FTX Futures', 'ADA-USD', '1h'),
    ('FTX Futures', 'ATOM-USD', '1h'),
    ('FTX Futures', 'XRP-USD', '1h'),
    ('FTX Futures', 'LTC-USD', '1h'),
    # ('FTX Futures', '1INCH-USD', '1h'),
    ('FTX Futures', 'BCH-USD', '1h'),
]
