jesse import-candles "FTX Futures" QTUM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ETH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ADA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XRP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BTC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BNB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NEO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LTC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SOL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TRX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LINK-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BCH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AVAX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FTM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ETC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" EOS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XLM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" 1INCH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DOT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FIL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MATIC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BTT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AAVE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SAND-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" IOTA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LUNA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" UNI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NEAR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ICP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALGO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ATOM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SRM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XTZ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KAVA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RVN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZEC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DASH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NANO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" OMG-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ARPA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CRV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" THETA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ONT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CELR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ICX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NULS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" VET-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" WAVES-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZIL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZRX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BAT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ENJ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DUSK-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" WIN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TOMO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DENT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FUN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CVC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" REN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KAVA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" VITE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DATA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CHR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" GXS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ARDR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LRC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" COMP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SXP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DGB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" STORJ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MANA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BLZ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KMD-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ANT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KSM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RUNE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" WING-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NBS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ORN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XEM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" GRT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BADGER-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XMR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" YFI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HOT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DOGE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AXS-USD %1 --skip-confirmation
echo off
echo Done
pause
