:: FTX pairs sorted by daily perpetual volume (at 2021-09-23)

jesse import-candles "FTX Futures" BTC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ETH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SOL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AVAX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FTT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ATOM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LUNA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ADA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DOT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MATIC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XRP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LINK-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALGO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XTZ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FTM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SRM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AXS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DOGE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DYDX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BNB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SUSHI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LTC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" EOS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NEAR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SLP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BCH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" OMG-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" UNI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CRV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RUNE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AAVE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FIL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RAY-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" EGLD-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" VET-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HBAR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XLM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TRX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" THETA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DEFI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" GRT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" 1INCH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FLOW-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SAND-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" COMP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SNX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CHZ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ICP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KSM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" STEP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ETC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SXP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" USDT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ENJ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AGLD-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AUDIO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" NEO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZEC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALPHA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" C98-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" YFI-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BSV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CAKE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CVC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ATLAS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CLV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MID-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" REN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DASH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ONE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MKR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TRU-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CRO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BTT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" IOTA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KAVA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" EXCH-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" PERP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XMR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" PRIV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" WAVES-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SHIT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RSR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZIL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALICE-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CREAM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" POLIS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HOT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KIN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BADGER-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SHIB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" YFII-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" RAMP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MNGO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" KNC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" STMX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ONT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ICX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" STX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TOMO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" QTUM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BAT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BAND-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SKL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" REEF-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HNT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ZRX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DRGN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BAL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TULIP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MANA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DENT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XEM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LINA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" OKB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" EDEN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CHR-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MTL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CEL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DODO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" PROM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" STORJ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MTA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ROOK-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" UNISWAP-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" XAUT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LRC-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MAPS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TLM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" PUNDIX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" PAXG-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" OXY-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FLM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" FIDA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" DAWN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ALCX-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" CONV-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SECO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BAO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MEDIA-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HOLY-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BNT-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" HUM-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MER-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" SRN-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" LEO-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ORBS-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" AMPL-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" TRYB-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MVDA25-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" BRZ-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" ASD-USD %1 --skip-confirmation
jesse import-candles "FTX Futures" MVDA10-USD %1 --skip-confirmation
echo off
echo Done
pause
