jesse import-candles "Binance Futures" BTC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ETH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SOL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DYDX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FTM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AVAX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LUNA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FIL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ADA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" COTI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XRP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" UNI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DOT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BNB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ATOM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CELR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XTZ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LINK-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SUSHI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LTC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" EOS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ALGO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DOGE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CRV-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MATIC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AXS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SRM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" REN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ONE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ETC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BCH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ICP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AAVE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" 1INCH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ALICE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NEAR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BZRX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" OMG-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TRX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BAKE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" GALA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" THETA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" EGLD-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RUNE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" IOTX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" C98-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TLM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" IOST-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KSM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SXP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" VET-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XLM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RAY-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" GRT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KAVA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MASK-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DODO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RLC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" 1000SHIB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" COMP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" WAVES-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CHR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XMR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ICX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" HBAR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SAND-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DENT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NEO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SNX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" 1000XEC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZEC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CHZ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" YFI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" IOTA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BAL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" QTUM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZEN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DASH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AKRO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MANA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MKR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ENJ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CTK-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TOMO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LINA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" HOT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ALPHA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SFP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" STORJ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CVC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" OGN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BEL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KEEP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ONT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AUDIO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BTT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BAND-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BLZ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" STMX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LIT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SKL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" REEF-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" HNT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TRB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FLM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BTS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MTL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RVN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZIL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" YFII-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZRX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LRC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RSR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NKN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BAT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ATA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" GTC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KNC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XEM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" OCEAN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CELO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" UNFI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ANKR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DGB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DEFI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BTCDOM-USDT %1 --skip-confirmation
echo Done
pause
