jesse import-candles "Binance Futures" BTC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ETH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BNB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TRX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NEO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AAVE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" QTUM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LTC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ADA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XRP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" EOS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XLM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" IOTA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ONT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ETC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ICX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NULS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" VET-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LINK-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" WAVES-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BTT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" HOT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZIL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZRX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BAT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XMR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ZEC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CELR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DASH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NANO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" OMG-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" THETA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ENJ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MATIC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FTM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DOGE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DUSK-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" WIN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" TOMO-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DENT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FUN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CVC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BEAM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RVN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" REN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KAVA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ARPA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BCH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" VITE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FTT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DATA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CHR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" GXS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ARDR-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LRC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" COMP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SC-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SXP-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DGB-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" STORJ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" MANA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" YFI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SOL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BLZ-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KMD-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ANT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" SAND-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CRV-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" DOT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" LUNA-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" KSM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" RUNE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" WING-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" UNI-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" NBS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AVAX-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" ORN-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" FIL-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" AXS-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" XEM-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" GRT-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" 1INCH-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" CAKE-USDT %1 --skip-confirmation
jesse import-candles "Binance Futures" BADGER-USDT %1 --skip-confirmation
echo off
echo Done
pause