jesse import-candles Binance BTC-USDT %1 --skip-confirmation
jesse import-candles Binance ETH-USDT %1 --skip-confirmation
jesse import-candles Binance BNB-USDT %1 --skip-confirmation
jesse import-candles Binance TRX-USDT %1 --skip-confirmation
jesse import-candles Binance NEO-USDT %1 --skip-confirmation
jesse import-candles Binance QTUM-USDT %1 --skip-confirmation
jesse import-candles Binance LTC-USDT %1 --skip-confirmation
jesse import-candles Binance ADA-USDT %1 --skip-confirmation
jesse import-candles Binance XRP-USDT %1 --skip-confirmation
jesse import-candles Binance EOS-USDT %1 --skip-confirmation
jesse import-candles Binance XLM-USDT %1 --skip-confirmation
jesse import-candles Binance IOTA-USDT %1 --skip-confirmation
jesse import-candles Binance ONT-USDT %1 --skip-confirmation
jesse import-candles Binance ETC-USDT %1 --skip-confirmation
jesse import-candles Binance ICX-USDT %1 --skip-confirmation
jesse import-candles Binance NULS-USDT %1 --skip-confirmation
jesse import-candles Binance VET-USDT %1 --skip-confirmation
jesse import-candles Binance LINK-USDT %1 --skip-confirmation
jesse import-candles Binance WAVES-USDT %1 --skip-confirmation
jesse import-candles Binance BTT-USDT %1 --skip-confirmation
jesse import-candles Binance HOT-USDT %1 --skip-confirmation
jesse import-candles Binance ZIL-USDT %1 --skip-confirmation
jesse import-candles Binance ZRX-USDT %1 --skip-confirmation
jesse import-candles Binance BAT-USDT %1 --skip-confirmation
jesse import-candles Binance XMR-USDT %1 --skip-confirmation
jesse import-candles Binance ZEC-USDT %1 --skip-confirmation
jesse import-candles Binance CELR-USDT %1 --skip-confirmation
jesse import-candles Binance DASH-USDT %1 --skip-confirmation
jesse import-candles Binance NANO-USDT %1 --skip-confirmation
jesse import-candles Binance OMG-USDT %1 --skip-confirmation
jesse import-candles Binance THETA-USDT %1 --skip-confirmation
jesse import-candles Binance ENJ-USDT %1 --skip-confirmation
jesse import-candles Binance MATIC-USDT %1 --skip-confirmation
jesse import-candles Binance FTM-USDT %1 --skip-confirmation
jesse import-candles Binance DOGE-USDT %1 --skip-confirmation
jesse import-candles Binance DUSK-USDT %1 --skip-confirmation
jesse import-candles Binance WIN-USDT %1 --skip-confirmation
jesse import-candles Binance TOMO-USDT %1 --skip-confirmation
jesse import-candles Binance DENT-USDT %1 --skip-confirmation
jesse import-candles Binance FUN-USDT %1 --skip-confirmation
jesse import-candles Binance CVC-USDT %1 --skip-confirmation
jesse import-candles Binance BEAM-USDT %1 --skip-confirmation
jesse import-candles Binance RVN-USDT %1 --skip-confirmation
jesse import-candles Binance REN-USDT %1 --skip-confirmation
jesse import-candles Binance KAVA-USDT %1 --skip-confirmation
jesse import-candles Binance ARPA-USDT %1 --skip-confirmation
jesse import-candles Binance BCH-USDT %1 --skip-confirmation
jesse import-candles Binance VITE-USDT %1 --skip-confirmation
jesse import-candles Binance FTT-USDT %1 --skip-confirmation
jesse import-candles Binance DATA-USDT %1 --skip-confirmation
jesse import-candles Binance CHR-USDT %1 --skip-confirmation
jesse import-candles Binance GXS-USDT %1 --skip-confirmation
jesse import-candles Binance ARDR-USDT %1 --skip-confirmation
jesse import-candles Binance LRC-USDT %1 --skip-confirmation
jesse import-candles Binance COMP-USDT %1 --skip-confirmation
jesse import-candles Binance SC-USDT %1 --skip-confirmation
jesse import-candles Binance SXP-USDT %1 --skip-confirmation
jesse import-candles Binance DGB-USDT %1 --skip-confirmation
jesse import-candles Binance STORJ-USDT %1 --skip-confirmation
jesse import-candles Binance MANA-USDT %1 --skip-confirmation
jesse import-candles Binance YFI-USDT %1 --skip-confirmation
jesse import-candles Binance SOL-USDT %1 --skip-confirmation
jesse import-candles Binance BLZ-USDT %1 --skip-confirmation
jesse import-candles Binance KMD-USDT %1 --skip-confirmation
jesse import-candles Binance ANT-USDT %1 --skip-confirmation
jesse import-candles Binance SAND-USDT %1 --skip-confirmation
jesse import-candles Binance CRV-USDT %1 --skip-confirmation
jesse import-candles Binance DOT-USDT %1 --skip-confirmation
jesse import-candles Binance LUNA-USDT %1 --skip-confirmation
jesse import-candles Binance KSM-USDT %1 --skip-confirmation
jesse import-candles Binance RUNE-USDT %1 --skip-confirmation
jesse import-candles Binance WING-USDT %1 --skip-confirmation
jesse import-candles Binance UNI-USDT %1 --skip-confirmation
jesse import-candles Binance NBS-USDT %1 --skip-confirmation
jesse import-candles Binance AVAX-USDT %1 --skip-confirmation
jesse import-candles Binance ORN-USDT %1 --skip-confirmation
jesse import-candles Binance FIL-USDT %1 --skip-confirmation
jesse import-candles Binance AAVE-USDT %1 --skip-confirmation
jesse import-candles Binance AXS-USDT %1 --skip-confirmation
jesse import-candles Binance XEM-USDT %1 --skip-confirmation
jesse import-candles Binance GRT-USDT %1 --skip-confirmation
jesse import-candles Binance 1INCH-USDT %1 --skip-confirmation
jesse import-candles Binance CAKE-USDT %1 --skip-confirmation
jesse import-candles Binance BADGER-USDT %1 --skip-confirmation
echo off
echo Done
pause