routes = [
    # ('Binance Futures', 'AXS-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'BTC-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'DENT-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'DGB-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'FIL-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'LINA-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'MKR-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'RSR-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'SC-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'SUSHI-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),
    # ('Binance Futures', 'ZEC-USDT', '5m', 'OttBands5minFixed', 'vNqn]'),

    # ('Binance Futures', 'AAVE-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    #
    # ('Binance Futures', 'BAL-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    ('Binance Futures', 'BNB-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    ('Binance Futures', '1INCH-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    ('Binance Futures', 'BAKE-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'BTT-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'C98-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'CHR-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'CHZ-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'COTI-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'CTK-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'CVC-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'DEFI-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'DODO-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'DOT-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'ETH-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'KSM-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'LINK-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'OCEAN-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'ONT-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'SC-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'STORJ-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    #
    # ('Binance Futures', 'TRB-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'TRX-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'XLM-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'XTZ-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),
    # ('Binance Futures', 'ZRX-USDT', '5m', 'OttBands5minFixed', 'WrVZ;'),

]

extra_candles = []
